Update playwright.yml
test

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,83 +1,117 @@
 name: Playwright Tests
-
-on:
+'on':
   push:
-    branches: [dev2]
+    branches:
+      - dev2
   workflow_dispatch:
-      inputs:
-        testTag:
-          description: 'Select the type of tests to run'
-          required: true
-          type: choice
-          options:
-            - sanity
-            - smoke
-          default: 'sanity'  # Default tag
-
+    inputs:
+      testTag:
+        description: Select the type of tests to run
+        required: true
+        type: choice
+        default: sanity
+        options:
+          - sanity
+          - smoke
+          - e2e
 jobs:
+  setup-shard:
+    runs-on: ubuntu-latest
+    outputs:
+      shard-index: '${{ steps.set-shard-index.outputs.shardIndex }}'
+      testFile: '${{ steps.set-shard-index.outputs.testFile }}'
+    steps:
+      - name: Set shardIndex and testFile based on testTag
+        id: set-shard-index
+        run: |
+          if [[ "${{ github.event.inputs.testTag }}" == "smoke" ]]; then
+            echo "::set-output name=shardIndex::[1,2,3]"
+            echo "::set-output name=testFile::smoke.yml"
+          elif [[ "${{ github.event.inputs.testTag }}" == "e2e" ]]; then
+            echo "::set-output name=shardIndex::[1]"
+            echo "::set-output name=testFile::e2e.yml"
+          else
+            echo "::set-output name=shardIndex::[1]"
+            echo "::set-output name=testFile::sanity.yml"
+          fi
   playwright-tests:
-    timeout-minutes: 2
+    needs: setup-shard
+    timeout-minutes: 120
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        shardIndex: [1]
-        shardTotal: [1]
+        shardIndex: '${{ fromJSON(needs.setup-shard.outputs[''shard-index'']) }}'
+        shardTotal:
+          - 3
     steps:
-      - uses: actions/checkout@v4
-
+      - name: Checkout repository
+        uses: actions/checkout@v4
       - name: Cache Node.js modules
         uses: actions/cache@v2
         with:
           path: ~/.npm
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          key: '${{ runner.os }}-node-${{ hashFiles(''**/package-lock.json'') }}'
           restore-keys: |
             ${{ runner.os }}-node-
-
       - name: Install js-yaml
         run: npm install js-yaml
-
-      - uses: actions/setup-node@v4
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
         with:
           node-version: 19
-
       - name: Install dependencies
         run: npm ci
-
       - name: Install Playwright browsers
         run: npx playwright install
-
       - name: Read yaml
         uses: mikefarah/yq@master
         id: read_yaml
         with:
-          cmd: yq eval '.shards[${{ matrix.shardIndex }}].tests | .[]' .github/workflows/test_mapping.yml 
-      
+          cmd: >-
+            yq eval '.shards[${{ matrix.shardIndex }}].tests | .[]'
+            .github/workflows/${{ needs.setup-shard.outputs.testFile }}
+      - name: Download .last-failed artifact (if available)
+        uses: actions/download-artifact@v3
+        with:
+          name: last-failed-file
+          path: playwright-report/.last-failed
+          if-no-files-found: ignore
       - name: Running tests
-        run: |
-            echo "test starting test::"
-            shard_tests="${{ steps.read_yaml.outputs.result }}"
-            echo "Shard tests are: $shard_tests"
-            shard_index=${{ matrix.shardIndex }}
-            echo "Shard tests for shard $shard_index :: "            
-            
-            # Remove leading and trailing whitespaces from shard_tests
-            shard_tests=$(echo "$shard_tests" | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//')
-            
-            echo "Running test : $shard_tests"
-            
-            # Replace newlines with spaces
-            shard_tests=$(echo "$shard_tests" | tr '\n' ' ')
-            echo "Running tests with tag: ${{ github.event.inputs.testTag }}"
-            npx playwright test --grep @${{ github.event.inputs.testTag }} $tests --workers=4
-        
-        
-      
-      
+        id: run-tests
+        run: >
+          echo "Test starting:"
 
+          shard_tests="${{ steps.read_yaml.outputs.result }}"
+
+          shard_index=${{ matrix.shardIndex }}
+
+          echo "Shard tests for shard $shard_index:"
+
+          shard_tests=$(echo "$shard_tests" | sed -e 's/^[ \t]*//' -e 's/[
+          \t]*$//')
+
+          shard_tests=$(echo "$shard_tests" | tr '\n' ' ')
+
+          echo "Running tests with tag: ${{ github.event.inputs.testTag }}"
+
+
+          if [ -f "playwright-report/.last-failed" ]; then
+            echo "Re-running failed tests from .last-failed..."
+            npx playwright test --last-failed || true
+          else
+            echo "Running specified shard tests..."
+            npx playwright test $shard_tests --workers=4 || true
+          fi
+      - name: Upload .last-failed artifact
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: last-failed-file
+          path: playwright-report/.last-failed
       - name: Upload blob report to GitHub Actions Artifacts
         uses: actions/upload-artifact@v3
         with:
-          name: blob-report-${{ matrix.shardIndex }}
+          name: 'blob-report-${{ matrix.shardIndex }}'
           path: blob-report
           retention-days: 1
